---

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    indent-sequences: consistent
  line-length:
    max: 196
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable

ignore: |
  **/node_modules/**
  **/vendor/**
  **/dist/**
  **/build/**
  .pixi/envs/
  **/.pixi/envs/**
  **/dbt_packages/**
  **.pixi/solve-group-envs/**
